# Generated by Django 4.1.1 on 2022-09-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('text', models.TextField()),
            ],
        ),
    ]
